### ISSUE TITLE
PrismaClientExceptionFilter still throw 500

### ISSUE THREAD

**Issue by conioX** [notiz-dev/nestjs-prisma#36]
Hi Guys, i try example fastify from this library

and connect with my database, my service only like this : 

```
  users() {
    return this.prisma.users.findFirstOrThrow({
      where: { user_id: 'My User Id' },
    });
  }
```

but reponse still throw error 500 

```
{
    "statusCode": 500,
    "message": "Internal server error"
}
```

**Comment by marcjulian** [comment]
@conioX thanks for bringing this up. I'm guessing you have added the `PrismaClientExceptionFilter` to your `main.ts` and are still receiving this 500er code?

```ts
//src/main.ts
import { ValidationPipe } from '@nestjs/common';
import { HttpAdapterHost, NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { PrismaClientExceptionFilter } from 'nestjs-prisma';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const { httpAdapter } = app.get(HttpAdapterHost);
  app.useGlobalFilters(new PrismaClientExceptionFilter(httpAdapter));

  await app.listen(3000);
}
bootstrap();
```

I can replicate it in the [fastify example](https://github.com/notiz-dev/nestjs-prisma/tree/main/examples/fastify) too. The reason is that `PrismaClient` has multiple different [exception types](https://www.prisma.io/docs/reference/api-reference/error-reference). The `PrismaClientExceptionFilter` catches at the moment only exceptions of the type `PrismaClientKnownRequestError`. 

`findFirstOrThrow` and `findUniqueOrThrow` are not throwing `PrismaClientKnownRequestError` instead they throw `NotFoundError`. 

It will be great to add `NotFoundError` to the  `PrismaClientExceptionFilter`.

**Comment by marcjulian** [comment]
`NotFoundError` will now also be handled by `PrismaClientExceptionFilter`. Try it out in the latest dev release

```bash
npm i nestjs-prisma@0.19.0-dev.1
```
